site_name: "Leeway"
site_description: "Bread and butter box pushing bread slices under butter knives. Hints from previous runs are taken."

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://git.sr.ht/~sthagen/leeway
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/leeway
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: sthagen/leeway
repo_url: https://git.sr.ht/~sthagen/leeway
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - API: 'api.md'
  - Changes: 'changes.md'
  - Contribute: 'contribute.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
